var data = [
  {
    id: 1,
    name: 'admin',
    status: '已启用',
    isManger: '是',
    role: '管理员',
    group: '青岛办事处',
    ename: 'admin',
    phone: '13312238907',
    sex: '男',
    mail: 'sefhaj@123.com',
    remark: '备注而已'
  },
  {
    id: 2,
    name: 'admin',
    status: '已启用',
    isManger: '是',
    role: '管理员',
    group: '青岛办事处',
    ename: 'admin',
    phone: '13312238907',
    sex: '男',
    mail: 'sefhaj@123.com',
    remark: '备注而已'
  },
  {
    id: 3,
    name: 'admin',
    status: '已启用',
    isManger: '是',
    role: '管理员',
    group: '青岛办事处',
    ename: 'admin',
    phone: '13312238907',
    sex: '男',
    mail: 'sefhaj@123.com',
    remark: '备注而已'
  },
  {
    id: 4,
    name: 'admin',
    status: '已启用',
    isManger: '是',
    role: '管理员',
    group: '青岛办事处',
    ename: 'admin',
    phone: '13312238907',
    sex: '男',
    mail: 'sefhaj@123.com',
    remark: '备注而已'
  },
  {
    id: 5,
    name: 'admin',
    status: '已启用',
    isManger: '是',
    role: '管理员',
    group: '青岛办事处',
    ename: 'admin',
    phone: '13312238907',
    sex: '男',
    mail: 'sefhaj@123.com',
    remark: '备注而已'
  },
  {
    id: 6,
    name: 'admin',
    status: '已启用',
    isManger: '是',
    role: '管理员',
    group: '青岛办事处',
    ename: 'admin',
    phone: '13312238907',
    sex: '男',
    mail: 'sefhaj@123.com',
    remark: '备注而已'
  },
  {
    id: 7,
    name: 'admin',
    status: '已启用',
    isManger: '是',
    role: '管理员',
    group: '青岛办事处',
    ename: 'admin',
    phone: '13312238907',
    sex: '男',
    mail: 'sefhaj@123.com',
    remark: '备注而已'
  },
  {
    id: 8,
    name: 'admin',
    status: '已启用',
    isManger: '是',
    role: '管理员',
    group: '青岛办事处',
    ename: 'admin',
    phone: '13312238907',
    sex: '男',
    mail: 'sefhaj@123.com',
    remark: '备注而已'
  },
  {
    id: 9,
    name: 'admin',
    status: '已启用',
    isManger: '是',
    role: '管理员',
    group: '青岛办事处',
    ename: 'admin',
    phone: '13312238907',
    sex: '男',
    mail: 'sefhaj@123.com',
    remark: '备注而已'
  },
  {
    id: 10,
    name: 'admin',
    status: '已启用',
    isManger: '是',
    role: '管理员',
    group: '青岛办事处',
    ename: 'admin',
    phone: '13312238907',
    sex: '男',
    mail: 'sefhaj@123.com',
    remark: '备注而已'
  },
  {
    id: 11,
    name: 'admin',
    status: '已启用',
    isManger: '是',
    role: '管理员',
    group: '青岛办事处',
    ename: 'admin',
    phone: '13312238907',
    sex: '男',
    mail: 'sefhaj@123.com',
    remark: '备注而已'
  },
  {
    id: 12,
    name: 'admin',
    status: '已启用',
    isManger: '是',
    role: '管理员',
    group: '青岛办事处',
    ename: 'admin',
    phone: '13312238907',
    sex: '男',
    mail: 'sefhaj@123.com',
    remark: '备注而已'
  }
];

export default data;
